Cd 543 tests passing
CancerDataAggregator/cda-python pull request #212
Opened 2023-10-06 22:28 UTC by dionboles-asym

This updates cdapython to the latest BQ code, handles offset and limit , adds unique_terms as a Q object, and adds the latest cda_client for postgres

2023-10-06 22:31 UTC, otchet-broad commented
Tests are failing at the moment because the bee appears to be down.  @ahaessly - Is it possible to allow the BEE to run 24/7?

2023-10-11 12:59 UTC, otchet-broad requested changes
Just a few items to clean up and to see if we can get the tests running, one-by-one again now that counts are enabled.

2023-11-03 17:41 UTC, ACharbonneau commented on cdapython/Q.py
>                  )
I don't understand why this requires one or three arguments. And I write the documentation.

2023-11-03 17:49 UTC, ACharbonneau commented on cdapython/Q.py
>      def mutation(self) -> Q:
The method defined on line 473 above is not needed/should be removed.

2023-11-03 18:20 UTC, ACharbonneau commented on cdapython/Q.py
This function https://github.com/CancerDataAggregator/cda-python/blob/d4720eab60a862bf36e7bbd5c8d77771f080f727/cdapython/Q.py#L349 has an incorrect error message https://github.com/CancerDataAggregator/cda-python/blob/d4720eab60a862bf36e7bbd5c8d77771f080f727/cdapython/Q.py#L388C15-L388C78 txt, csv, and tsv are all supported

2023-11-03 18:22 UTC, ACharbonneau commented on cdapython/Q.py
https://github.com/CancerDataAggregator/cda-python/blob/d4720eab60a862bf36e7bbd5c8d77771f080f727/cdapython/Q.py#L403 definition includes options not documented in docstring

2023-11-03 18:46 UTC, ACharbonneau commented on cdapython/Q.py
Our documentation doesn't cover this, can you tell me what I need to add please

https://github.com/CancerDataAggregator/cda-python/blob/d4720eab60a862bf36e7bbd5c8d77771f080f727/cdapython/Q.py#L764

2023-11-22 19:13 UTC, closed without merging