Bugfix/issue26 support system in uniq values
CancerDataAggregator/cda-python pull request #31
Opened 2021-06-28 18:14 UTC by fkaufman-asym

This PR removes the native python unique_terms code and simply calls the cda-service API call in it's place.  The optional system attribute has been enabled to match the ability to filter eq. GDC, PDC

2021-06-28 21:14 UTC, pshapiro4broad requested changes
Looks good, I believe more code deletion is possible here.

2021-06-28 21:14 UTC, pshapiro4broad commented on cdapython.py
> -            _new_system, _unnest_system = _get_unnest_clause(col_name='ResearchSubject.identifier.system')
Now that this is deleted, you can also delete `_get_unnest_clause` below.

2021-06-28 21:14 UTC, pshapiro4broad commented on notebooks/example.ipynb
> +   "execution_count": 3,
Even if you use the notebook for testing, I would avoid updating it unless you're making a change to the example, or if the output has changed and you want to show the updated output in the notebook preview. So in this case I would revert the changes to this file.

2021-06-29 14:31 UTC, dionboles-asym approved these changes

2021-06-29 16:51 UTC, pshapiro4broad approved these changes
Lgtm

2021-06-30 14:29 UTC, merged