Bigquerystatuscheck
CancerDataAggregator/cda-python pull request #36
Opened 2021-07-22 14:14 UTC by dionboles-asym

#34 This add's a status check for big-query for the cda-python

2021-07-23 09:32 UTC, nemanjab17 approved these changes

2021-08-05 19:06 UTC, fkaufman-asym commented on notebooks/example.ipynb
> +      "\n    label: TCGA-E2-A10A-01Z-00-DX1.98B19EF1-0DAE-4DC6-8B0E-963CFABC6724.svs\n \n    drs_uri: drs://dg.4DFC:99a00a9f-c4bf-49ca-9c3d-435f0a207644\n\n    byte_size: 1341476123\n\n    \n\n    la
Phil suggested that we avoid changing the state of the JupyterNotebooks unless we are actually updating the functionality.   I am thinking that we should put the *.ipynb into the .gitignore file for the most part unless we are checking in a new notebook.

2021-08-05 19:21 UTC, fkaufman-asym requested changes
I'm thinking we should add the .ipynb to .gitignore before pushing.

2021-08-11 15:37 UTC, fkaufman-asym approved these changes

2021-08-11 15:38 UTC, merged